import { calculateCosts, fail, LOCAL_CHAIN_ID, parseUint } from "../domain/model.ts";
import { computePlanId } from "../domain/identity.ts";
import type { ApprovedArtifact, TrustRoots } from "../adapters/artifact.ts";
export interface StablePlan { readonly schemaVersion: 1; readonly kind: "deployment-plan"; readonly planId: `0x${string}`; readonly identity: Record<string, unknown>; readonly broadcastAllowed: false; readonly testOnly: true; readonly productionApproved: false; readonly mainnetAllowed: false }
export interface QuoteObservation { readonly chainId: string; readonly blockNumber: string; readonly blockHash: `0x${string}`; readonly blockTimestamp: string; readonly currentHeadNumber: string; readonly currentHeadHash: `0x${string}`; readonly feeHistoryNewestBlock: string; readonly gasEstimate: string; readonly blockGasLimit: string; readonly baseFeePerGas: string; readonly maxPriorityFeePerGas: string; readonly maxFeePerGas: string; readonly observedAt: string }
export interface FeeQuote { readonly schemaVersion: 1; readonly kind: "fee-quote"; readonly planId: `0x${string}`; readonly creationInputHash: string; readonly observation: QuoteObservation; readonly bufferBps: string; readonly gasLimit: string; readonly effectiveFeePerGas: string; readonly estimatedWei: string; readonly worstCaseWei: string; readonly expiresAt: string; readonly informationalUsd?: string }
export function buildStablePlan(approved: ApprovedArtifact, roots: TrustRoots): StablePlan {
  if (roots.chainId !== LOCAL_CHAIN_ID || !roots.testOnly || roots.productionApproved || roots.mainnetAllowed) fail("TRUST_ROOTS_UNSAFE", "trust roots are not local test-only roots");
  const identity: Record<string, unknown> = { contractFqn: roots.contractFqn, buildProfile: roots.buildProfile, sourceDependencyClosure: approved.sourceDependencyClosure, buildInfoSha256: approved.buildInfoSha256, artifactSha256: approved.artifactSha256, abiSha256: approved.abiSha256, fixtureSha256: approved.fixtureSha256, fixtureReadySha256: roots.fixtureReadySha256, solcVersion: approved.solcVersion, compilerSettings: approved.compilerSettings, creationBytecodeHash: approved.creationBytecodeHash, constructorAbiBytes: approved.constructorAbiBytes, constructorAbiHash: approved.constructorAbiHash, constructorArguments: approved.constructorArguments, constructorArgumentsHash: approved.constructorArgumentsHash, creationInputHash: approved.creationInputHash, chainId: roots.chainId, from: roots.from, value: "0", capPolicy: { maximumWorstCaseWei: roots.maximumWorstCaseWei, testOnly: true }, broadcastAllowed: false };
  return { schemaVersion: 1, kind: "deployment-plan", planId: computePlanId(identity), identity, broadcastAllowed: false, testOnly: true, productionApproved: false, mainnetAllowed: false };
}
export function buildFeeQuote(plan: StablePlan, observation: QuoteObservation, roots: TrustRoots): FeeQuote {
  if (observation.chainId !== roots.chainId) fail("WRONG_CHAIN", "observed chain does not match approved chain");
  const block = parseUint(observation.blockNumber, "blockNumber"); const head = parseUint(observation.currentHeadNumber, "currentHeadNumber"); const newest = parseUint(observation.feeHistoryNewestBlock, "feeHistoryNewestBlock"); const timestamp = parseUint(observation.blockTimestamp, "blockTimestamp"); const observedAt = parseUint(observation.observedAt, "observedAt"); const ttl = parseUint(roots.quoteTtlSeconds, "quoteTtlSeconds", false);
  if (block > head || newest > head) fail("FUTURE_BLOCK", "quote references a future block");
  if (head - block > parseUint(roots.maximumHeadLag, "maximumHeadLag")) fail("HEAD_LAG", "quote block is too far behind head");
  if (newest !== block) fail("FEE_HISTORY_BLOCK_MISMATCH", "fee history is not bound to estimate block");
  if (timestamp > observedAt) fail("FUTURE_TIMESTAMP", "block timestamp is in the future");
  if (observedAt - timestamp > ttl) fail("STALE_QUOTE", "block timestamp is stale");
  if (!/^0x[0-9a-f]{64}$/u.test(observation.blockHash) || !/^0x[0-9a-f]{64}$/u.test(observation.currentHeadHash)) fail("BLOCK_HASH_INVALID", "block hash is malformed");
  if (block === head && observation.blockHash !== observation.currentHeadHash) fail("REORGED_BLOCK", "head hash differs from the bound estimate block");
  const costs = calculateCosts({ gasEstimate: parseUint(observation.gasEstimate, "gasEstimate", false), bufferBps: parseUint(roots.gasBufferBps, "gasBufferBps"), baseFeePerGas: parseUint(observation.baseFeePerGas, "baseFeePerGas"), maxPriorityFeePerGas: parseUint(observation.maxPriorityFeePerGas, "maxPriorityFeePerGas"), maxFeePerGas: parseUint(observation.maxFeePerGas, "maxFeePerGas"), value: 0n, blockGasLimit: parseUint(observation.blockGasLimit, "blockGasLimit", false), maximumWorstCaseWei: parseUint(roots.maximumWorstCaseWei, "maximumWorstCaseWei") });
  return { schemaVersion: 1, kind: "fee-quote", planId: plan.planId, creationInputHash: String(plan.identity.creationInputHash), observation, bufferBps: roots.gasBufferBps, gasLimit: String(costs.gasLimit), effectiveFeePerGas: String(costs.effectiveFee), estimatedWei: String(costs.estimatedWei), worstCaseWei: String(costs.worstCaseWei), expiresAt: String(observedAt + ttl) };
}
